name: "development_release"

on:
  push:
    branches:
      - devb
    tags:
      - "v*"

jobs:
  development-release:
    name: "Development Release"
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8.
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Python BrainSpace.
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel

    - name: Build binary wheel and tarball.
      run: |
        python setup.py sdist bdist_wheel

    - name: Publish to PyPi test.
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_TEST_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/